<a href="https://colab.research.google.com/github/devannaalandra/Desain-dan-analisis-algoritma/blob/main/DAA_Pert2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
DataMahasiswa = ["Devanna", 2021071039, "INFORMATIKA", "DAA", "14/09/2022", "Universitas Pembangunan Jaya"]
print (DataMahasiswa)

['Devanna', 2021071039, 'INFORMATIKA', 'DAA', '14/09/2022', 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [ ]:
DataMahasiswa[1]

2021071039

In [ ]:
DataMahasiswa[5]

'Universitas Pembangunan Jaya'

In [ ]:
bin_colors[0:2]

['Red', 'Green']

In [ ]:
DataMahasiswa[1:3]

[2021071039, 'INFORMATIKA']

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print (aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
DataMahasiswa = ["Devanna", 2021071039, "INFORMATIKA", "DAA", "14/09/2022", "Universitas Pembangunan Jaya"]
for UPJ in DataMahasiswa:
  print ("UPJ " , UPJ)

UPJ  Devanna
UPJ  2021071039
UPJ  INFORMATIKA
UPJ  DAA
UPJ  14/09/2022
UPJ  Universitas Pembangunan Jaya


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[2:]

['Blue', 'Yellow']

In [ ]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [ ]:
nested_tuple = ( 100, [200, 400, 600], 300,  [400, 800])
nested_tuple[2]

300

In [ ]:
bin_colors2 = {"manual_color":"Yellow", "approved_color":"Green", "refused_color":"Red"}
print (bin_colors2)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors2['approved_color']

'Green'

In [ ]:
bin_colors2['approved_color']='Purple'
print (bin_colors2)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
DataMahasiswa2 = {'Nama':'Devanna', 'NIM': 2021071039, 'Prodi':'Informatika', 'Universitas':'UPJ'}
print (DataMahasiswa2)

{'Nama': 'Devanna', 'NIM': 2021071039, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
green = {'grass', 'leaves'}
print (green)

{'grass', 'leaves'}


In [ ]:
green = {'grass', 'leaves', 'leaves'}
print (green)

{'grass', 'leaves'}


In [ ]:
yellow = {'dandelions', 'leaves','fire hydrants'}
red = {'fire hydrants', 'blood', 'leaves', 'rose'}
print (yellow|red)
print (yellow&red)

{'rose', 'fire hydrants', 'blood', 'dandelions', 'leaves'}
{'leaves', 'fire hydrants'}


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame([['1', 'Fares',32, True], ['2', 'Elena',23, False], ['3','Steven',40, True]])

In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc [:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [ ]:
df = pd.DataFrame([['1', 'Informatika', 50, 30, 20], 
                   ['2', 'Sistem Informasi', 55, 30, 25], 
                   ['3', 'Teknik Sipil', 40, 30, 10]])

In [ ]:
df.columns = ['no', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

no             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [ ]:
myMatrix = np.array([
                    [11, 12, 13], 
                    [21, 22, 23],
                    [31, 32, 33]])
print (myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print (type(myMatrix))

<class 'numpy.ndarray'>


In [ ]:
print (type(myMatrix))

<class 'numpy.ndarray'>


In [ ]:
myMatrix2 = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800],
])
print (f'Original Array:\n{myMatrix2}')
myMatrix2_transposed = myMatrix2.transpose()
print (f'Transposed Array:\n{myMatrix2_transposed}')

Original Array:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transposed Array:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
myVector = [22, 33, 44, 55]
print (myVector)
print (type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [40]:
myVector = np.array ([22, 33, 44, 55])
print (myVector)
print (type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [41]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [42]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [43]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [44]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [45]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
